" Name:         Lost Shrine
" Description:  Dark, Elegant, Readable Color Scheme
" Author:       Sainnhepark <sainnhe@gmail.com>
" Maintainer:   Sainnhepark <sainnhe@gmail.com>
" Website:      https://github.com/sainnhe/vim-color-lost-shrine/
" License:      MIT && Anti-996
" Last Updated: Fri 05 Jul 2019 08:00:40 PM CST

" Generated by Colortemplate v2.0.0b3

set background=dark

hi clear
if exists('syntax_on')
  syntax reset
endif

let g:colors_name = 'lost-shrine'

let s:t_Co = exists('&t_Co') && !empty(&t_Co) && &t_Co > 1 ? &t_Co : 2
let s:italics = (((&t_ZH != '' && &t_ZH != '[7m') || has('gui_running')) && !has('iOS'))

hi! link QuickFixLine Search
hi! link StatusLineTerm StatusLine
hi! link StatusLineTermNC StatusLineNC
hi! link Structure Type
hi! link Boolean Constant
hi! link Define PreProc
hi! link SpecialChar Special
hi! link Debug Special
hi! link Include PreProc
hi! link Macro PreProc
hi! link Repeat Statement
hi! link lCursor Cursor

if (has('termguicolors') && &termguicolors) || has('gui_running')
  let g:terminal_ansi_colors = ['#434c5e', '#fd8e94', '#c7ecb0', '#fde4a8',
        \ '#c1d7fd', '#e3c3ff', '#b9f4e1', '#ebf0ca', '#434c5e', '#fd8e94',
        \ '#c7ecb0', '#fde4a8', '#c1d7fd', '#e3c3ff', '#b9f4e1', '#ebf0ca']
  if get(g:, 'dark_transp_bg', 0) && !has('gui_running')
    hi Normal guifg=#ebf0ca guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Terminal guifg=#ebf0ca guibg=NONE guisp=NONE gui=NONE cterm=NONE
  else
    hi Normal guifg=#ebf0ca guibg=#2e3440 guisp=NONE gui=NONE cterm=NONE
    hi Terminal guifg=#ebf0ca guibg=#2e3440 guisp=NONE gui=NONE cterm=NONE
  endif
  hi ColorColumn guifg=fg guibg=#2e3440 guisp=NONE gui=NONE cterm=NONE
  hi Conceal guifg=#707f9c guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Cursor guifg=#ebf0ca guibg=#2e3440 guisp=NONE gui=NONE cterm=NONE
  hi CursorColumn guifg=NONE guibg=#434c5e guisp=NONE gui=NONE cterm=NONE
  hi CursorLine guifg=NONE guibg=#434c5e guisp=NONE gui=NONE cterm=NONE
  hi CursorLineNr guifg=#ebf0ca guibg=#434c5e guisp=NONE gui=NONE cterm=NONE
  hi LineNr guifg=#707f9c guibg=#434c5e guisp=NONE gui=NONE cterm=NONE
  hi SignColumn guifg=NONE guibg=#434c5e guisp=NONE gui=NONE cterm=NONE
  hi DiffAdd guifg=NONE guibg=#2d3a2c guisp=NONE gui=NONE cterm=NONE
  hi DiffChange guifg=NONE guibg=#303e56 guisp=NONE gui=NONE cterm=NONE
  hi DiffDelete guifg=NONE guibg=#4b323b guisp=NONE gui=NONE cterm=NONE
  hi DiffText guifg=NONE guibg=#473628 guisp=NONE gui=NONE cterm=NONE
  hi Directory guifg=#c7ecb0 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi EndOfBuffer guifg=#434c5e guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi ErrorMsg guifg=#fd8e94 guibg=#434c5e guisp=NONE gui=NONE cterm=NONE
  hi WarningMsg guifg=#fdc59f guibg=#434c5e guisp=NONE gui=NONE cterm=NONE
  hi ModeMsg guifg=#2e3440 guibg=#c7ecb0 guisp=NONE gui=bold cterm=bold
  hi MoreMsg guifg=#2e3440 guibg=#c1d7fd guisp=NONE gui=NONE cterm=NONE
  hi FoldColumn guifg=#707f9c guibg=#434c5e guisp=NONE gui=NONE cterm=NONE
  hi Folded guifg=#707f9c guibg=#434c5e guisp=NONE gui=NONE cterm=NONE
  hi Pmenu guifg=#ebf0ca guibg=#434c5e guisp=NONE gui=NONE cterm=NONE
  hi PmenuSel guifg=#2e3440 guibg=#c7ecb0 guisp=NONE gui=NONE cterm=NONE
  hi PmenuSbar guifg=NONE guibg=#434c5e guisp=NONE gui=NONE cterm=NONE
  hi PmenuThumb guifg=NONE guibg=#c7ecb0 guisp=NONE gui=NONE cterm=NONE
  hi Question guifg=#c7ecb0 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi SpellBad guifg=#c1d7fd guibg=NONE guisp=#fd8e94 gui=NONE cterm=NONE
  hi SpellCap guifg=#fdc59f guibg=NONE guisp=#fdc59f gui=NONE cterm=NONE
  hi SpellLocal guifg=#c7ecb0 guibg=NONE guisp=#b9f4e1 gui=NONE cterm=NONE
  hi SpellRare guifg=#e3c3ff guibg=NONE guisp=#e3c3ff gui=NONE cterm=NONE
  hi VertSplit guifg=#707f9c guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Visual guifg=NONE guibg=#58647a guisp=NONE gui=NONE cterm=NONE
  hi VisualNOS guifg=NONE guibg=#58647a guisp=NONE gui=italic cterm=italic
  hi Search guifg=NONE guibg=#58647a guisp=NONE gui=underline cterm=underline
  hi IncSearch guifg=NONE guibg=#58647a guisp=NONE gui=underline cterm=underline
  hi MatchParen guifg=NONE guibg=NONE guisp=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
  hi NonText guifg=#707f9c guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi StatusLine guifg=#ebf0ca guibg=#58647a guisp=NONE gui=NONE cterm=NONE
  hi StatusLineNC guifg=#2e3440 guibg=#58647a guisp=NONE gui=NONE cterm=NONE
  hi TabLine guifg=#2e3440 guibg=#58647a guisp=NONE gui=NONE cterm=NONE
  hi TabLineFill guifg=#2e3440 guibg=#58647a guisp=NONE gui=NONE cterm=NONE
  hi TabLineSel guifg=#2e3440 guibg=#c1d7fd guisp=NONE gui=NONE cterm=NONE
  hi WildMenu guifg=#2e3440 guibg=#c7ecb0 guisp=NONE gui=NONE cterm=NONE
  hi Title guifg=#e3c3ff guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Label guifg=#e3c3ff guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Conditional guifg=#e3c3ff guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Todo guifg=#e3c3ff guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi PreCondit guifg=#e3c3ff guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Typedef guifg=#fde4a8 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi PreProc guifg=#fde4a8 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Keyword guifg=#fde4a8 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Operator guifg=#fde4a8 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Delimiter guifg=#fde4a8 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Type guifg=#c7ecb0 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi StorageClass guifg=#c7ecb0 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Tag guifg=#c7ecb0 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi String guifg=#c7ecb0 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Character guifg=#c7ecb0 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Number guifg=#c7ecb0 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Float guifg=#c7ecb0 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Identifier guifg=#c1d7fd guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Function guifg=#c1d7fd guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Statement guifg=#c1d7fd guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Constant guifg=#c1d7fd guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Special guifg=#c1d7fd guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Exception guifg=#fdc59f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi SpecialKey guifg=#e3c3ff guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Error guifg=#fd8e94 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi Comment guifg=#707f9c guibg=NONE guisp=NONE gui=italic cterm=italic
  hi SpecialComment guifg=#dbc08d guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Ignore guifg=#707f9c guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Underlined guifg=NONE guibg=NONE guisp=NONE gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
  hi CursorIM guifg=NONE guibg=fg guisp=NONE gui=NONE cterm=NONE
  hi ToolbarLine guifg=NONE guibg=#707f9c guisp=NONE gui=NONE cterm=NONE
  hi ToolbarButton guifg=#2e3440 guibg=#ebf0ca guisp=NONE gui=bold cterm=bold
  if !s:italics
    hi VisualNOS gui=NONE cterm=NONE
    hi Comment gui=NONE cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 256
  if get(g:, 'dark_transp_bg', 0)
    hi Normal ctermfg=230 ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=230 ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=230 ctermbg=236 cterm=NONE
    if !has('patch-8.0.0616') " Fix for Vim bug
      set background=dark
    endif
    hi Terminal ctermfg=230 ctermbg=236 cterm=NONE
  endif
  hi ColorColumn ctermfg=fg ctermbg=236 cterm=NONE
  hi Conceal ctermfg=67 ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=230 ctermbg=236 cterm=NONE
  hi CursorColumn ctermfg=NONE ctermbg=239 cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=239 cterm=NONE
  hi CursorLineNr ctermfg=230 ctermbg=239 cterm=NONE
  hi LineNr ctermfg=67 ctermbg=239 cterm=NONE
  hi SignColumn ctermfg=NONE ctermbg=239 cterm=NONE
  hi DiffAdd ctermfg=NONE ctermbg=237 cterm=NONE
  hi DiffChange ctermfg=NONE ctermbg=237 cterm=NONE
  hi DiffDelete ctermfg=NONE ctermbg=237 cterm=NONE
  hi DiffText ctermfg=NONE ctermbg=237 cterm=NONE
  hi Directory ctermfg=193 ctermbg=NONE cterm=NONE
  hi EndOfBuffer ctermfg=239 ctermbg=NONE cterm=NONE
  hi ErrorMsg ctermfg=210 ctermbg=239 cterm=NONE
  hi WarningMsg ctermfg=223 ctermbg=239 cterm=NONE
  hi ModeMsg ctermfg=236 ctermbg=193 cterm=bold
  hi MoreMsg ctermfg=236 ctermbg=153 cterm=NONE
  hi FoldColumn ctermfg=67 ctermbg=239 cterm=NONE
  hi Folded ctermfg=67 ctermbg=239 cterm=NONE
  hi Pmenu ctermfg=230 ctermbg=239 cterm=NONE
  hi PmenuSel ctermfg=236 ctermbg=193 cterm=NONE
  hi PmenuSbar ctermfg=NONE ctermbg=239 cterm=NONE
  hi PmenuThumb ctermfg=NONE ctermbg=193 cterm=NONE
  hi Question ctermfg=193 ctermbg=NONE cterm=NONE
  hi SpellBad ctermfg=153 ctermbg=NONE cterm=NONE
  hi SpellCap ctermfg=223 ctermbg=NONE cterm=NONE
  hi SpellLocal ctermfg=193 ctermbg=NONE cterm=NONE
  hi SpellRare ctermfg=183 ctermbg=NONE cterm=NONE
  hi VertSplit ctermfg=67 ctermbg=NONE cterm=NONE
  hi Visual ctermfg=NONE ctermbg=60 cterm=NONE
  hi VisualNOS ctermfg=NONE ctermbg=60 cterm=italic
  hi Search ctermfg=NONE ctermbg=60 cterm=underline
  hi IncSearch ctermfg=NONE ctermbg=60 cterm=underline
  hi MatchParen ctermfg=NONE ctermbg=NONE cterm=bold
  hi NonText ctermfg=67 ctermbg=NONE cterm=NONE
  hi StatusLine ctermfg=230 ctermbg=60 cterm=NONE
  hi StatusLineNC ctermfg=236 ctermbg=60 cterm=NONE
  hi TabLine ctermfg=236 ctermbg=60 cterm=NONE
  hi TabLineFill ctermfg=236 ctermbg=60 cterm=NONE
  hi TabLineSel ctermfg=236 ctermbg=153 cterm=NONE
  hi WildMenu ctermfg=236 ctermbg=193 cterm=NONE
  hi Title ctermfg=183 ctermbg=NONE cterm=NONE
  hi Label ctermfg=183 ctermbg=NONE cterm=NONE
  hi Conditional ctermfg=183 ctermbg=NONE cterm=NONE
  hi Todo ctermfg=183 ctermbg=NONE cterm=NONE
  hi PreCondit ctermfg=183 ctermbg=NONE cterm=NONE
  hi Typedef ctermfg=222 ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=222 ctermbg=NONE cterm=NONE
  hi Keyword ctermfg=222 ctermbg=NONE cterm=NONE
  hi Operator ctermfg=222 ctermbg=NONE cterm=NONE
  hi Delimiter ctermfg=222 ctermbg=NONE cterm=NONE
  hi Type ctermfg=193 ctermbg=NONE cterm=NONE
  hi StorageClass ctermfg=193 ctermbg=NONE cterm=NONE
  hi Tag ctermfg=193 ctermbg=NONE cterm=NONE
  hi String ctermfg=193 ctermbg=NONE cterm=NONE
  hi Character ctermfg=193 ctermbg=NONE cterm=NONE
  hi Number ctermfg=193 ctermbg=NONE cterm=NONE
  hi Float ctermfg=193 ctermbg=NONE cterm=NONE
  hi Identifier ctermfg=153 ctermbg=NONE cterm=NONE
  hi Function ctermfg=153 ctermbg=NONE cterm=NONE
  hi Statement ctermfg=153 ctermbg=NONE cterm=NONE
  hi Constant ctermfg=153 ctermbg=NONE cterm=NONE
  hi Special ctermfg=153 ctermbg=NONE cterm=NONE
  hi Exception ctermfg=223 ctermbg=NONE cterm=NONE
  hi SpecialKey ctermfg=183 ctermbg=NONE cterm=NONE
  hi Error ctermfg=210 ctermbg=NONE cterm=bold
  hi Comment ctermfg=67 ctermbg=NONE cterm=italic
  hi SpecialComment ctermfg=180 ctermbg=NONE cterm=NONE
  hi Ignore ctermfg=67 ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=NONE ctermbg=NONE cterm=underline
  hi CursorIM ctermfg=NONE ctermbg=fg cterm=NONE
  hi ToolbarLine ctermfg=NONE ctermbg=67 cterm=NONE
  hi ToolbarButton ctermfg=236 ctermbg=230 cterm=bold
  if !s:italics
    hi VisualNOS cterm=NONE
    hi Comment cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 8
  if get(g:, 'dark_transp_bg', 0)
    hi Normal ctermfg=White ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=White ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=White ctermbg=Black cterm=NONE
    hi Terminal ctermfg=White ctermbg=Black cterm=NONE
  endif
  hi ColorColumn ctermfg=fg ctermbg=Black cterm=NONE
  hi Conceal ctermfg=LightGray ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=White ctermbg=Black cterm=NONE
  hi CursorColumn ctermfg=NONE ctermbg=DarkGrey cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=DarkGrey cterm=NONE
  hi CursorLineNr ctermfg=White ctermbg=DarkGrey cterm=NONE
  hi LineNr ctermfg=LightGray ctermbg=DarkGrey cterm=NONE
  hi SignColumn ctermfg=NONE ctermbg=DarkGrey cterm=NONE
  hi DiffAdd ctermfg=NONE ctermbg=DarkGreen cterm=NONE
  hi DiffChange ctermfg=NONE ctermbg=DarkBlue cterm=NONE
  hi DiffDelete ctermfg=NONE ctermbg=DarkRed cterm=NONE
  hi DiffText ctermfg=NONE ctermbg=DarkYellow cterm=NONE
  hi Directory ctermfg=Green ctermbg=NONE cterm=NONE
  hi EndOfBuffer ctermfg=DarkGrey ctermbg=NONE cterm=NONE
  hi ErrorMsg ctermfg=Red ctermbg=DarkGrey cterm=NONE
  hi WarningMsg ctermfg=DarkYellow ctermbg=DarkGrey cterm=NONE
  hi ModeMsg ctermfg=Black ctermbg=Green cterm=bold
  hi MoreMsg ctermfg=Black ctermbg=Blue cterm=NONE
  hi FoldColumn ctermfg=LightGray ctermbg=DarkGrey cterm=NONE
  hi Folded ctermfg=LightGray ctermbg=DarkGrey cterm=NONE
  hi Pmenu ctermfg=White ctermbg=DarkGrey cterm=NONE
  hi PmenuSel ctermfg=Black ctermbg=Green cterm=NONE
  hi PmenuSbar ctermfg=NONE ctermbg=DarkGrey cterm=NONE
  hi PmenuThumb ctermfg=NONE ctermbg=Green cterm=NONE
  hi Question ctermfg=Green ctermbg=NONE cterm=NONE
  hi SpellBad ctermfg=Blue ctermbg=NONE cterm=NONE
  hi SpellCap ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi SpellLocal ctermfg=Green ctermbg=NONE cterm=NONE
  hi SpellRare ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi VertSplit ctermfg=LightGray ctermbg=NONE cterm=NONE
  hi Visual ctermfg=NONE ctermbg=Gray cterm=NONE
  hi VisualNOS ctermfg=NONE ctermbg=Gray cterm=italic
  hi Search ctermfg=NONE ctermbg=Gray cterm=underline
  hi IncSearch ctermfg=NONE ctermbg=Gray cterm=underline
  hi MatchParen ctermfg=NONE ctermbg=NONE cterm=bold
  hi NonText ctermfg=LightGray ctermbg=NONE cterm=NONE
  hi StatusLine ctermfg=White ctermbg=Gray cterm=NONE
  hi StatusLineNC ctermfg=Black ctermbg=Gray cterm=NONE
  hi TabLine ctermfg=Black ctermbg=Gray cterm=NONE
  hi TabLineFill ctermfg=Black ctermbg=Gray cterm=NONE
  hi TabLineSel ctermfg=Black ctermbg=Blue cterm=NONE
  hi WildMenu ctermfg=Black ctermbg=Green cterm=NONE
  hi Title ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi Label ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi Conditional ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi Todo ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi PreCondit ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi Typedef ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi Keyword ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi Operator ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi Delimiter ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi Type ctermfg=Green ctermbg=NONE cterm=NONE
  hi StorageClass ctermfg=Green ctermbg=NONE cterm=NONE
  hi Tag ctermfg=Green ctermbg=NONE cterm=NONE
  hi String ctermfg=Green ctermbg=NONE cterm=NONE
  hi Character ctermfg=Green ctermbg=NONE cterm=NONE
  hi Number ctermfg=Green ctermbg=NONE cterm=NONE
  hi Float ctermfg=Green ctermbg=NONE cterm=NONE
  hi Identifier ctermfg=Blue ctermbg=NONE cterm=NONE
  hi Function ctermfg=Blue ctermbg=NONE cterm=NONE
  hi Statement ctermfg=Blue ctermbg=NONE cterm=NONE
  hi Constant ctermfg=Blue ctermbg=NONE cterm=NONE
  hi Special ctermfg=Blue ctermbg=NONE cterm=NONE
  hi Exception ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi SpecialKey ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi Error ctermfg=Red ctermbg=NONE cterm=bold
  hi Comment ctermfg=LightGray ctermbg=NONE cterm=italic
  hi SpecialComment ctermfg=Brown ctermbg=NONE cterm=NONE
  hi Ignore ctermfg=LightGray ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=NONE ctermbg=NONE cterm=underline
  hi CursorIM ctermfg=NONE ctermbg=fg cterm=NONE
  hi ToolbarLine ctermfg=NONE ctermbg=LightGray cterm=NONE
  hi ToolbarButton ctermfg=Black ctermbg=White cterm=bold
  if !s:italics
    hi VisualNOS cterm=NONE
    hi Comment cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 2
  hi Normal term=NONE
  hi ColorColumn term=reverse
  hi Conceal term=NONE
  hi Cursor term=NONE
  hi CursorColumn term=reverse
  hi CursorLine term=underline
  hi CursorLineNr term=bold,italic,reverse,underline
  hi DiffAdd term=reverse,underline
  hi DiffChange term=reverse,underline
  hi DiffDelete term=reverse,underline
  hi DiffText term=bold,reverse,underline
  hi Directory term=NONE
  hi EndOfBuffer term=NONE
  hi ErrorMsg term=bold,italic,reverse
  hi FoldColumn term=reverse
  hi Folded term=italic,reverse,underline
  hi IncSearch term=bold,italic,reverse
  hi LineNr term=reverse
  hi MatchParen term=bold,underline
  hi ModeMsg term=NONE
  hi MoreMsg term=NONE
  hi NonText term=NONE
  hi Pmenu term=reverse
  hi PmenuSbar term=NONE
  hi PmenuSel term=NONE
  hi PmenuThumb term=NONE
  hi Question term=standout
  hi Search term=italic,underline
  hi SignColumn term=reverse
  hi SpecialKey term=bold
  hi SpellBad term=italic,underline
  hi SpellCap term=italic,underline
  hi SpellLocal term=italic,underline
  hi SpellRare term=italic,underline
  hi StatusLine term=bold,reverse
  hi StatusLineNC term=reverse
  hi TabLine term=italic,reverse,underline
  hi TabLineFill term=reverse,underline
  hi TabLineSel term=bold
  hi Title term=bold
  hi VertSplit term=reverse
  hi Visual term=reverse
  hi VisualNOS term=NONE
  hi WarningMsg term=standout
  hi WildMenu term=bold
  hi Comment term=italic
  hi Constant term=bold,italic
  hi Error term=reverse
  hi Identifier term=italic
  hi Ignore term=NONE
  hi PreProc term=italic
  hi Special term=bold,italic
  hi Statement term=bold
  hi Todo term=bold,underline
  hi Type term=bold
  hi Underlined term=underline
  hi CursorIM term=NONE
  hi ToolbarLine term=reverse
  hi ToolbarButton term=bold,reverse
  if !s:italics
    hi CursorLineNr term=bold,reverse,underline
    hi ErrorMsg term=bold,reverse
    hi Folded term=reverse,underline
    hi IncSearch term=bold,reverse
    hi Search term=underline
    hi SpellBad term=underline
    hi SpellCap term=underline
    hi SpellLocal term=underline
    hi SpellRare term=underline
    hi TabLine term=reverse,underline
    hi Comment term=NONE
    hi Constant term=bold
    hi Identifier term=NONE
    hi PreProc term=NONE
    hi Special term=bold
  endif
  unlet s:t_Co s:italics
  finish
endif

" Background: dark
" Color: dark          #2e3440           ~                 Black
" Color: darkgrey      #434c5e           ~                 DarkGrey
" Color: grey          #707f9c           ~                 LightGray
" Color: greyalt       #58647a           ~                 Gray
" Color: light         #ebf0ca           ~                 White
" Color: green         #c7ecb0           ~                 Green
" Color: blue          #c1d7fd           ~                 Blue
" Color: magenta       #e3c3ff           ~                 Magenta
" Color: yellow        #fde4a8           ~                 Yellow
" Color: orange        #fdc59f           ~                 DarkYellow
" Color: red           #fd8e94           ~                 Red
" Color: cyan          #b9f4e1           ~                 Cyan
" Color: brown         #dbc08d           ~                 Brown
" Color: darkred       #4b323b           ~                 DarkRed
" Color: darkgreen     #2d3a2c           ~                 DarkGreen
" Color: darkorange    #473628           ~                 DarkYellow
" Color: darkblue      #303e56           ~                 DarkBlue
" Term colors: darkgrey red green yellow blue magenta cyan light
" Term colors: darkgrey red green yellow
" Term colors: blue magenta cyan light
" Color: unused #000000 0 0
